config/routes.rb
Tr8nSample::Application.routes.draw do
  mount WillFilter::Engine => "/will_filter"
  mount Tr8n::Engine => "/tr8n"
  devise_for :users

  resources :schools

  
  root :to =>"schools#index"

end

app/models/school.rb
class School < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  def admin?
    true
  end

  def guest?
    false
  end
  
  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_filter :authenticate_user!
  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schools }
    end
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
    @school = School.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/new
  # GET /schools/new.json
  def new
    @school = School.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/1/edit
  def edit
    @school = School.find(params[:id])
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(params[:school])

    respond_to do |format|
      if @school.save
        trfn 'School was successfully created.'
        format.html { redirect_to @school}
        format.json { render json: @school, status: :created, location: @school }
      else
        trfe 'Please correct these error to continue.'

        format.html { render action: "new" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schools/1
  # PUT /schools/1.json
  def update
    @school = School.find(params[:id])

    respond_to do |format|
      if @school.update_attributes(params[:school])
        trfn 'School was successfully updated.'
        format.html { redirect_to @school }
        format.json { head :ok }
      else
        trfe 'Please correct following errors to update.'

        format.html { render action: "edit" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school = School.find(params[:id])
    @school.destroy
    trfe 'deleted successfuly'

    respond_to do |format|
      format.html { redirect_to schools_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tr8nSample</title>
    <%= tr8n_scripts_tag %>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= flash[:trfn] %>
    <div style="float:right;">
      <%= tr8n_language_selector_tag %>
    </div>
    <%= yield %>

    <%= tr8n_language_strip_tag %>

  </body>
</html>

app/views/layouts/tr8n.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
		<title><%=trl("Tr8n Engine Plugin", "Application title")%></title>
		<%= stylesheet_link_tag("tr8n/layout") %>
		<%= stylesheet_link_tag("tr8n/components") %>
		<%= tr8n_scripts_tag %>
	</head>
  <body>
    <div class="document">
			<div class="page_head">
			  <div class="page_fixed">
			    <div class="mrgn_h">
				    <ul class="flt_r horiz_list top_nav">
			        <li><%= tr8n_language_selector_tag(:lightbox=>false) %></li>
			  		</ul>
			      <h1 class="logo"><%=tr("Tr8n Translation Engine", "Application title")%></h1>
			    </div>
			  </div>
			</div>

			<div class="page_fixed">
			    <%= tr8n_flashes_tag %>
			</div>

      <div class="page_fixed">
        <div class="page_body">
          <div class="content_module">
            <div class="content_inner">
              <%= yield %>
            </div>
          </div>
        </div>
				<div class="page_ft module quiet">
				  <ul class="flt_r right_horiz_list">
				    <li><%=link_to(tr("Home"), "/", :class => "quiet")%></li>
				    <li><%=link_to(tr("Languages"), "/tr8n/language/table", :class => "quiet")%></li>
				    <li><%=link_to(tr("Translator Tools"), "/tr8n/dashboard", :class => "quiet")%></li>
				    <li><%=link_to(tr("Administration Tools"), "/tr8n/admin/language", :class => "quiet")%></li>
				    <li><%=link_to(tr("Credits"), "/tr8n/help/credits", :class => "quiet")%></li>
				    <li><%=link_to(tr("License"), "/tr8n/help/license", :class => "quiet")%></li>
				  </ul>
				  &copy; Copyright 2010 - 2012 tr8n.net
				</div>

				<div style="padding:15px;">
					<%= tr8n_language_strip_tag %>
				</div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/tr8n_admin.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
		<title><%=trl("Tr8n Engine Admin Tools", "Application title")%></title>
		<%= stylesheet_link_tag("tr8n/layout") %>
		<%= stylesheet_link_tag("tr8n/components") %>
		<%= tr8n_scripts_tag %>
		<style>
			.page_fixed {
				width:1200px;
			}
			.page_body {
				width:1200px;
			}
			 
			.wf_form {
				width: 99.8%;
			} 
		</style>
  </head>
  <body>
    <div class="document">
			<div class="page_head">
			  <div class="page_fixed">
			    <div class="mrgn_h">
				    <ul class="flt_r horiz_list top_nav">
			        <li><%= tr8n_language_selector_tag(:lightbox=>false) %></li>
			  		</ul>
			      <h1 class="logo"><%=link_to(tr("Tr8n Translation Engine", "Application title"), "/", :style=>"text-decorations:none;")%></h1>
			    </div>
			  </div>
			</div>

			<div class="page_fixed">
			    <%= tr8n_flashes_tag %>
			</div>
      <div class="page_fixed">
        <div class="page_body">
          <div class="content_module">
            <div class="content_inner">
              <%= yield %>
            </div>
          </div>
        </div>
				<div class="page_ft module quiet">
				  <ul class="flt_r right_horiz_list">
				    <li><%=link_to(tr("Home"), "/tr8n/home", :class => "quiet")%></li>
				    <li><%=link_to(tr("Languages"), "/tr8n/language/table", :class => "quiet")%></li>
				    <li><%=link_to(tr("Translator Tools"), "/tr8n/dashboard", :class => "quiet")%></li>
				    <li><%=link_to(tr("Administration Tools"), "/tr8n/admin/language", :class => "quiet")%></li>
				    <li><%=link_to(tr("Credits"), "/tr8n/help/credits", :class => "quiet")%></li>
				    <li><%=link_to(tr("License"), "/tr8n/help/license", :class => "quiet")%></li>
				  </ul>
				  &copy; Copyright 2010 - 2012 tr8n.net
				</div>

				<div style="padding:15px;">
					<%= tr8n_language_strip_tag %>
				</div>
      </div>
    </div>
  </body>
</html>

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :phone_num %><br />
    <%= f.text_field :phone_num %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing school</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<h1><%=tr "Listing schools"%></h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Phone num</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @schools.each do |school| %>
  <tr>
    <td><%= school.name %></td>
    <td><%= school.address %></td>
    <td><%= school.phone_num %></td>
    <td><%= link_to 'Show', school %></td>
    <td><%= link_to 'Edit', edit_school_path(school) %></td>
    <td><%= link_to 'Destroy', school, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New School', new_school_path %>

app/views/schools/new.html.erb
<h1>New school</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @school.name %>
</p>

<p>
  <b>Address:</b>
  <%= @school.address %>
</p>

<p>
  <b>Phone num:</b>
  <%= @school.phone_num %>
</p>


<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>